{"name": "test_invalid_login[credentials0]", "status": "failed", "statusDetails": {"message": "AssertionError: assert False\n +  where False = <bound method LoginPage.is_error_message_displayed of <src.pages.login.login_page.LoginPage object at 0x000002A5E6B00810>>()\n +    where <bound method LoginPage.is_error_message_displayed of <src.pages.login.login_page.LoginPage object at 0x000002A5E6B00810>> = <src.pages.login.login_page.LoginPage object at 0x000002A5E6B00810>.is_error_message_displayed", "trace": "driver_manager = <src.utils.driver_manager.DriverManager object at 0x000002A5E6AE0150>, credentials = {'password': 'invalid_password', 'username': 'invalid_user@example.com'}\n\n>   ???\nE   assert False\nE    +  where False = <bound method LoginPage.is_error_message_displayed of <src.pages.login.login_page.LoginPage object at 0x000002A5E6B00810>>()\nE    +    where <bound method LoginPage.is_error_message_displayed of <src.pages.login.login_page.LoginPage object at 0x000002A5E6B00810>> = <src.pages.login.login_page.LoginPage object at 0x000002A5E6B00810>.is_error_message_displayed\n\nd:\\Selenium Project\\web_automation_selenium - Copy\\src\\tests\\login\\test_login.py:32: AssertionError"}, "parameters": [{"name": "credentials", "value": "{'username': 'invalid_user@example.com', 'password': 'invalid_password'}"}], "start": 1730954407163, "stop": 1730954417883, "uuid": "ace48e98-e5d8-4870-b065-443770f9fe01", "historyId": "cefd590ba46851b50d50bcd8ccba11e6", "testCaseId": "3c0037dd2b68679f213f9e135d1736b3", "fullName": "src.tests.login.test_login#test_invalid_login", "labels": [{"name": "parentSuite", "value": "src.tests.login"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "DESKTOP-1ML9BAE"}, {"name": "thread", "value": "21724-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "src.tests.login.test_login"}]}